---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver-pvc
  namespace: microservices-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  namespace: microservices-platform
  labels:
    app: cloudbeaver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
        - name: cloudbeaver
          image: dbeaver/cloudbeaver:23.3.5
          ports:
            - containerPort: 8978
          env:
            - name: CLOUDBEAVER_FORCE_HTTPS
              value: "false"
            - name: CB_ADMIN_NAME
              value: "admin"
            - name: CB_ADMIN_PASSWORD
              value: "password123"
          volumeMounts:
            - name: cloudbeaver-data
              mountPath: /opt/cloudbeaver/workspace/.data
            
            # ĐƯA FILE NÀY VÀO GLOBAL CONFIGURATION ĐỂ SKIP WIZARD
            - name: cloudbeaver-config-volume
              mountPath: /opt/cloudbeaver/workspace/GlobalConfiguration/cloudbeaver.conf
              subPath: cloudbeaver.conf
            
            # Giữ nguyên đường dẫn này vì trong file config đang trỏ tới đây
            - name: cloudbeaver-config-volume
              mountPath: /opt/cloudbeaver/conf/initial-data.conf
              subPath: initial-data.conf
              
            - name: cloudbeaver-config-volume
              mountPath: /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
              subPath: data-sources.json
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8978
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: cloudbeaver-data
          persistentVolumeClaim:
            claimName: cloudbeaver-pvc
        - name: cloudbeaver-config-volume
          configMap:
            name: cloudbeaver-config
---
apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver-service
  namespace: microservices-platform
spec:
  selector:
    app: cloudbeaver
  ports:
    - port: 8978
      targetPort: 8978
