version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: identity-postgres
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: identity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_admin -d identity_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-notification:
    image: postgres:15-alpine
    container_name: notification-postgres
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: notification_db
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_admin -d notification_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-cache:
    image: redis:7-alpine
    container_name: identity-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      redis-cache:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: platform-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: platform-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  # 2. Identity Service
  identity-service:
    image: identity-service
    build:
      context: .
      dockerfile: services/identity/Dockerfile
    container_name: identity-service
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    env_file:
      - services/identity/.env
    environment:
      # Overriding localhost from .env to use the internal docker network host
      - DATABASE_HOST=postgres-db
      - REDIS_HOST=redis-cache

  notification-service:
    image: notification-service
    build:
      context: .
      dockerfile: services/notification/Dockerfile
    container_name: notification-service
    ports:
      - "8082:8082"
    depends_on:
      postgres-notification:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    env_file:
      - services/notification/.env

volumes:
  postgres_data:
  postgres_notification_data:
