---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-notification
  namespace: microservices-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-notification
  template:
    metadata:
      labels:
        app: redis-notification
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: redis-notification-service
  namespace: microservices-platform
spec:
  type: ClusterIP
  selector:
    app: redis-notification
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
