// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notifications": {
            "get": {
                "description": "Returns paginated notification history for a user using cursor-based pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List notification history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (required)",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (pending|processing|sent|delivering|failed)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by channel (email|sms|zalo|push)",
                        "name": "channel",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by event type",
                        "name": "event_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time RFC3339 (e.g. 2026-01-01T00:00:00Z)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time RFC3339",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Opaque pagination cursor from previous response",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.ListNotificationsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/notifications/admin/campaigns": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create a mass notification campaign",
                "parameters": [
                    {
                        "description": "Campaign request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.CreateCampaignRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.CreateCampaignResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/notifications/admin/campaigns/{id}/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get campaign delivery stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.CampaignStatsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/notifications/admin/dlq/messages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List Dead Letter Queue messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (pending|replayed|ignored)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "messages": {
                                                    "type": "array",
                                                    "items": {
                                                        "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.DLQMessageResponse"
                                                    }
                                                },
                                                "total": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/notifications/admin/dlq/replay/{id}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Replay a Dead Letter Queue message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/notifications/health": {
            "get": {
                "description": "check service health",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.HealthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/notifications/send": {
            "post": {
                "description": "Direct trigger to send a notification (test or synchonous bypass of queue)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Send notification",
                "parameters": [
                    {
                        "description": "Notification Event",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.SendNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.SendNotificationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/notifications/webhooks/mailpit": {
            "post": {
                "description": "Callback from Mailpit when an email is received",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Handle Mailpit webhook",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/{id}/notification-preferences": {
            "get": {
                "description": "Returns toggleable notification preferences for a specific user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "preferences"
                ],
                "summary": "Get user notification preferences",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.GetPreferencesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "Upserts notification preferences for a user. Only promotion_campaign event is configurable.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "preferences"
                ],
                "summary": "Update user notification preferences",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Preferences payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.UpsertPreferencesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.UpsertPreferencesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/{id}/notification-schedules": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get all notification schedules for a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.GetSchedulesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "Creates or updates a daily notification schedule for a user (identified by path :id).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Set a recurring daily notification schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Schedule config",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.UpsertScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.ScheduleItem"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Delete a notification schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event type to delete",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.DeleteScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_tojinguyen_notification_internal_domain.CampaignStatus": {
            "type": "string",
            "enum": [
                "pending",
                "dispatching",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "CampaignStatusPending",
                "CampaignStatusDispatching",
                "CampaignStatusCompleted",
                "CampaignStatusFailed"
            ]
        },
        "github_com_tojinguyen_notification_internal_domain.EventType": {
            "type": "string",
            "enum": [
                "auth_otp",
                "auth_login_alert",
                "order_created",
                "payment_success",
                "promotion_campaign",
                "daily_reminder"
            ],
            "x-enum-varnames": [
                "EventOTP",
                "EventLoginAlert",
                "EventOrderCreated",
                "EventPaymentSuccess",
                "EventPromotion",
                "EventDailyReminder"
            ]
        },
        "github_com_tojinguyen_notification_internal_domain.NotificationChannel": {
            "type": "string",
            "enum": [
                "email",
                "sms",
                "zalo",
                "push"
            ],
            "x-enum-varnames": [
                "ChannelEmail",
                "ChannelSMS",
                "ChannelZalo",
                "ChannelPush"
            ]
        },
        "github_com_tojinguyen_notification_internal_domain.NotificationStatus": {
            "type": "string",
            "enum": [
                "pending",
                "processing",
                "sent",
                "delivering",
                "failed"
            ],
            "x-enum-varnames": [
                "NotificationStatusPending",
                "NotificationStatusProcessing",
                "NotificationStatusSent",
                "NotificationStatusDelivering",
                "NotificationStatusFailed"
            ]
        },
        "github_com_tojinguyen_notification_internal_dto.CampaignStatsResponse": {
            "type": "object",
            "properties": {
                "campaign_id": {
                    "type": "string"
                },
                "dispatched_count": {
                    "type": "integer"
                },
                "failed_count": {
                    "type": "integer"
                },
                "last_dispatched_offset": {
                    "type": "integer"
                },
                "pending_count": {
                    "type": "integer"
                },
                "progress_pct": {
                    "type": "number"
                },
                "sent_count": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.CampaignStatus"
                },
                "total_recipients": {
                    "type": "integer"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.CreateCampaignRequest": {
            "type": "object",
            "required": [
                "channel",
                "content",
                "event_type",
                "scheduled_at",
                "title"
            ],
            "properties": {
                "channel": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.NotificationChannel"
                },
                "content": {
                    "type": "string"
                },
                "event_type": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.EventType"
                },
                "recipients": {
                    "description": "Optional, only used when TargetAudience == \"specific\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.RecipientInput"
                    }
                },
                "scheduled_at": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "target_audience": {
                    "description": "e.g., \"all_users\", \"specific\"",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.CreateCampaignResponse": {
            "type": "object",
            "properties": {
                "campaign_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "scheduled_at": {
                    "type": "string"
                },
                "total_recipients": {
                    "type": "integer"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.DLQMessageResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "notification_id": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "queue_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.DeleteScheduleRequest": {
            "type": "object",
            "required": [
                "event_type"
            ],
            "properties": {
                "event_type": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.EventType"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.GetPreferencesResponse": {
            "type": "object",
            "properties": {
                "preferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.PreferenceItem"
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.GetSchedulesResponse": {
            "type": "object",
            "properties": {
                "schedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.ScheduleItem"
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.ListNotificationsResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.NotificationItem"
                    }
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.NotificationItem": {
            "type": "object",
            "properties": {
                "channel": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.NotificationChannel"
                },
                "created_at": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "event_type": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.EventType"
                },
                "id": {
                    "type": "string"
                },
                "recipient": {
                    "type": "string"
                },
                "retry_count": {
                    "type": "integer"
                },
                "sent_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.NotificationStatus"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.PreferenceItem": {
            "type": "object",
            "properties": {
                "channel": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.NotificationChannel"
                },
                "enabled": {
                    "type": "boolean"
                },
                "event_type": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.EventType"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.RecipientInput": {
            "type": "object",
            "required": [
                "recipient",
                "user_id"
            ],
            "properties": {
                "recipient": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.ScheduleItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "event_type": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.EventType"
                },
                "id": {
                    "type": "string"
                },
                "last_sent_at": {
                    "type": "string"
                },
                "send_time": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.SendNotificationRequest": {
            "type": "object",
            "required": [
                "event_type",
                "payload",
                "user_id"
            ],
            "properties": {
                "event_type": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.EventType"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": true
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.SendNotificationResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "notification_id": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.UpsertPreferenceItem": {
            "type": "object",
            "required": [
                "channel",
                "event_type"
            ],
            "properties": {
                "channel": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.NotificationChannel"
                },
                "enabled": {
                    "type": "boolean"
                },
                "event_type": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.EventType"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.UpsertPreferencesRequest": {
            "type": "object",
            "required": [
                "preferences"
            ],
            "properties": {
                "preferences": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.UpsertPreferenceItem"
                    }
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.UpsertPreferencesResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "preferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_tojinguyen_notification_internal_dto.PreferenceItem"
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_tojinguyen_notification_internal_dto.UpsertScheduleRequest": {
            "type": "object",
            "required": [
                "event_type",
                "send_time",
                "timezone",
                "user_id"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "event_type": {
                    "$ref": "#/definitions/github_com_tojinguyen_notification_internal_domain.EventType"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": true
                },
                "send_time": {
                    "description": "\"HH:MM\"",
                    "type": "string"
                },
                "timezone": {
                    "description": "IANA tz, e.g. \"Asia/Ho_Chi_Minh\"",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "response.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "meta": {},
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Notification Service API",
	Description:      "This is a notification service API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
