basePath: /api/v1/notifications
definitions:
  domain.EventType:
    enum:
    - auth_otp
    - auth_login_alert
    - order_created
    - payment_success
    - promotion_campaign
    type: string
    x-enum-varnames:
    - EventOTP
    - EventLoginAlert
    - EventOrderCreated
    - EventPaymentSuccess
    - EventPromotion
  dto.HealthResponse:
    properties:
      service:
        type: string
      status:
        type: string
    type: object
  dto.SendNotificationRequest:
    properties:
      event_type:
        $ref: '#/definitions/domain.EventType'
      metadata:
        additionalProperties: true
        type: object
      payload:
        additionalProperties: true
        type: object
      user_id:
        type: string
    required:
    - event_type
    - payload
    - user_id
    type: object
  dto.SendNotificationResponse:
    properties:
      message:
        type: string
      notification_id:
        type: string
    type: object
  response.StandardResponse:
    properties:
      data: {}
      error: {}
      meta: {}
      success:
        type: boolean
    type: object
host: localhost
info:
  contact: {}
  description: This is a notification service API
  title: Notification Service API
  version: "1.0"
paths:
  /health:
    get:
      description: check service health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.HealthResponse'
              type: object
      summary: Health check
      tags:
      - health
  /send:
    post:
      consumes:
      - application/json
      description: Direct trigger to send a notification (test or synchonous bypass
        of queue)
      parameters:
      - description: Notification Event
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/dto.SendNotificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.SendNotificationResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                error:
                  properties:
                    code:
                      type: integer
                    message:
                      type: string
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                error:
                  properties:
                    code:
                      type: integer
                    message:
                      type: string
                  type: object
              type: object
      summary: Send notification
      tags:
      - notifications
  /webhooks/mailpit:
    post:
      consumes:
      - application/json
      description: Callback from Mailpit when an email is received
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Handle Mailpit webhook
      tags:
      - webhooks
swagger: "2.0"
