apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  PORT: "8080"
  TIME_GRACE: "10"
  DATABASE_HOST: "postgres-service" # Point to the postgres service in Kubernetes
  DATABASE_PORT: "5432"
  DATABASE_USER: "user_admin"
  DATABASE_DBNAME: "identity_db"
  DATABASE_SSLMODE: "disable"
  JWT_ISSUER: "identity-service"
  JWT_ACCESS_TOKEN_LIFESPAN: "24"
  JWT_REFRESH_TOKEN_LIFESPAN: "168"
  GOOGLE_OAUTH_CLIENT_ID: "653255842498-4vst9cdn5oukr77qen519abu2aul8hql.apps.googleusercontent.com"
  GOOGLE_OAUTH_REDIRECT_URL: "http://localhost:8081/api/v1/auth/google/callback"