apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
type: Opaque
stringData:
  DATABASE_PASSWORD: "password123"
  JWT_SECRET_KEY: "PhaiThayDoiKeyNayKhiLenProduction123!"
  GOOGLE_OAUTH_CLIENT_SECRET: "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"