grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /grafana
    hosts:
      - localhost
  grafana.ini:
    server:
      domain: localhost
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
    date_formats:
      default_timezone: Asia/Ho_Chi_Minh
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          access: proxy
          isDefault: false
          jsonData:
            timeInterval: "15s"

promtail:
  enabled: true
  config:
    snippets:
      pipelineStages:
        - cri: {}
        # Chỉ xử lý những dòng log có định dạng JSON (bắt đầu bằng "{")
        - match:
            selector: '{app!=""}'
            stages:
              - json:
                  expressions:
                    level: level
                    service: service
              # Bỏ qua dòng không phải JSON
              - drop:
                  expression: '^[^{]'
              - labels:
                  level: ''
                  service: ''


loki:
  isDefault: true
  persistence:
    enabled: true
    size: 5Gi
