grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: LoadBalancer
  grafana.ini:
    date_formats:
      default_timezone: Asia/Ho_Chi_Minh
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          access: proxy
          isDefault: false
          jsonData:
            timeInterval: "15s"

promtail:
  enabled: true
  config:
    snippets:
      pipelineStages:
        - docker: {}

loki:
  isDefault: true
  persistence:
    enabled: true
    size: 5Gi
