grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: NodePort
    nodePort: 32000
  grafana.ini:
    date_formats:
      default_timezone: Asia/Ho_Chi_Minh

promtail:
  enabled: true
  config:
    snippets:
      pipelineStages:
        - docker: {}

loki:
  isDefault: true
  persistence:
    enabled: true
    size: 5Gi
